#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import sys
import tempfile
from concurrent.futures import FIRST_COMPLETED, Future, ThreadPoolExecutor, wait
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_WORKERS = min(8, os.cpu_count() or 1)
SUPPORTED_COPY_MODES = ("copy", "hardlink", "symlink")


@dataclass(frozen=True)
class CopyJob:
    src: Path
    dst: Path
    rel: Path


@dataclass
class Summary:
    scanned: int = 0
    copied: int = 0
    conflicts: int = 0
    skipped: int = 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge a new XYZ tile pyramid into an existing master pyramid."
    )
    parser.add_argument("--master-pyramid", required=True, type=Path)
    parser.add_argument("--new-pyramid", required=True, type=Path)
    parser.add_argument("--conflicts-out", required=True, type=Path)
    parser.add_argument("--extension", default="png")
    parser.add_argument("--copy-mode", default="copy", choices=SUPPORTED_COPY_MODES)
    parser.add_argument("--workers", default=DEFAULT_WORKERS, type=positive_int)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--overwrite-conflicts-file", action="store_true")
    return parser.parse_args(argv)


def positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError("must be an integer") from None
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be at least 1")
    return parsed


def normalize_extension(extension: str) -> str:
    normalized = extension.strip().lstrip(".")
    if not normalized:
        raise ValueError("--extension must not be empty")
    if any(sep in normalized for sep in ("/", "\\")):
        raise ValueError("--extension must be a file extension, not a path")
    return normalized


def validate_inputs(args: argparse.Namespace) -> None:
    master = args.master_pyramid
    new = args.new_pyramid
    conflicts_out = args.conflicts_out

    if not master.exists():
        raise ValueError(f"master pyramid does not exist: {master}")
    if not master.is_dir():
        raise ValueError(f"master pyramid is not a directory: {master}")
    if not new.exists():
        raise ValueError(f"new pyramid does not exist: {new}")
    if not new.is_dir():
        raise ValueError(f"new pyramid is not a directory: {new}")
    if master.resolve() == new.resolve():
        raise ValueError("master pyramid and new pyramid must be different directories")
    if conflicts_out.exists() and not args.dry_run and not args.overwrite_conflicts_file:
        raise ValueError(
            f"conflict output already exists: {conflicts_out}. "
            "Use --overwrite-conflicts-file to replace it."
        )
    if conflicts_out.exists() and not args.dry_run and conflicts_out.is_dir():
        raise ValueError(f"conflict output is a directory: {conflicts_out}")
    conflicts_abs = conflicts_out.resolve(strict=False)
    new_abs = new.resolve()
    if conflicts_abs == new_abs or conflicts_abs.is_relative_to(new_abs):
        raise ValueError("conflict output must not be inside the new pyramid")


def iter_tile_files(new_pyramid: Path, extension: str):
    wanted_suffix = f".{extension.lower()}"
    for path in new_pyramid.rglob("*"):
        if not path.is_file():
            continue

        rel = path.relative_to(new_pyramid)
        if path.suffix.lower() != wanted_suffix:
            yield None, rel
            continue

        parts = rel.parts
        if len(parts) != 3:
            yield None, rel
            continue

        z, x, filename = parts
        y = Path(filename).stem
        if Path(filename).suffix.lower() == wanted_suffix and z.isdigit() and x.isdigit() and y.isdigit():
            yield path, rel
        else:
            yield None, rel


def conflict_header(args: argparse.Namespace, extension: str) -> str:
    generated = (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )
    return "\n".join(
        [
            "# conflict file generated by merge.py",
            f"# generated={generated}",
            f"# master_pyramid={args.master_pyramid.resolve()}",
            f"# new_pyramid={args.new_pyramid.resolve()}",
            f"# extension={extension}",
            "# format=relative_xyz_path",
            "",
        ]
    )


def atomic_copy(job: CopyJob, copy_mode: str) -> Path:
    job.dst.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = job.dst.with_name(f".{job.dst.name}.{os.getpid()}.{id(job)}.tmp")

    try:
        if copy_mode == "copy":
            shutil.copy2(job.src, tmp_path)
        elif copy_mode == "hardlink":
            os.link(job.src, tmp_path)
        elif copy_mode == "symlink":
            os.symlink(job.src.resolve(), tmp_path)
        else:
            raise ValueError(f"unsupported copy mode: {copy_mode}")

        os.replace(tmp_path, job.dst)
    except Exception:
        try:
            tmp_path.unlink()
        except FileNotFoundError:
            pass
        raise

    return job.rel


def submit_copy(
    executor: ThreadPoolExecutor,
    pending: set[Future[Path]],
    job: CopyJob,
    copy_mode: str,
    summary: Summary,
    verbose: bool,
    max_pending: int,
) -> None:
    pending.add(executor.submit(atomic_copy, job, copy_mode))
    drain_completed(pending, summary, verbose, max_pending=max_pending)


def drain_completed(
    pending: set[Future[Path]],
    summary: Summary,
    verbose: bool,
    max_pending: int = 0,
) -> None:
    while pending and (max_pending == 0 or len(pending) >= max_pending):
        done, pending_left = wait(pending, return_when=FIRST_COMPLETED)
        pending.clear()
        pending.update(pending_left)
        for future in done:
            rel = future.result()
            summary.copied += 1
            if verbose:
                print(f"copied {rel.as_posix()}", flush=True)
        if max_pending != 0:
            break


def write_conflict(conflicts_file, rel: Path, verbose: bool) -> None:
    conflicts_file.write(f"{rel.as_posix()}\n")
    if verbose:
        print(f"conflict {rel.as_posix()}", flush=True)


def run(args: argparse.Namespace) -> Summary:
    extension = normalize_extension(args.extension)
    validate_inputs(args)

    summary = Summary()
    conflicts_tmp_path: Path | None = None
    conflicts_file = None
    max_pending = max(args.workers * 4, 1)

    if not args.dry_run:
        args.conflicts_out.parent.mkdir(parents=True, exist_ok=True)
        tmp_handle = tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=args.conflicts_out.parent,
            prefix=f".{args.conflicts_out.name}.",
            suffix=".tmp",
            delete=False,
        )
        conflicts_file = tmp_handle
        conflicts_tmp_path = Path(tmp_handle.name)
        conflicts_file.write(conflict_header(args, extension))

    try:
        with ThreadPoolExecutor(max_workers=args.workers) as executor:
            pending: set[Future[Path]] = set()

            for src, rel in iter_tile_files(args.new_pyramid, extension):
                if src is None:
                    summary.skipped += 1
                    continue

                summary.scanned += 1
                dst = args.master_pyramid / rel
                if dst.exists():
                    summary.conflicts += 1
                    if conflicts_file is not None:
                        write_conflict(conflicts_file, rel, args.verbose)
                    elif args.verbose:
                        print(f"conflict {rel.as_posix()}", flush=True)
                    continue

                if args.dry_run:
                    summary.copied += 1
                    if args.verbose:
                        print(f"would copy {rel.as_posix()}", flush=True)
                    continue

                submit_copy(
                    executor,
                    pending,
                    CopyJob(src=src, dst=dst, rel=rel),
                    args.copy_mode,
                    summary,
                    args.verbose,
                    max_pending,
                )

            drain_completed(pending, summary, args.verbose)

        if conflicts_file is not None and conflicts_tmp_path is not None:
            conflicts_file.close()
            os.replace(conflicts_tmp_path, args.conflicts_out)
            conflicts_tmp_path = None

    finally:
        if conflicts_file is not None and not conflicts_file.closed:
            conflicts_file.close()
        if conflicts_tmp_path is not None:
            try:
                conflicts_tmp_path.unlink()
            except FileNotFoundError:
                pass

    return summary


def print_summary(args: argparse.Namespace, summary: Summary) -> None:
    print(f"Master pyramid: {args.master_pyramid.resolve()}")
    print(f"New pyramid: {args.new_pyramid.resolve()}")
    print(f"Conflict file: {args.conflicts_out.resolve()}")
    print(f"Tiles scanned: {summary.scanned}")
    print(f"Tiles copied: {summary.copied}")
    print(f"Conflicts: {summary.conflicts}")
    print(f"Skipped non-tile files: {summary.skipped}")
    print(f"Dry run: {str(args.dry_run).lower()}")
    print("Done.")


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        summary = run(args)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print_summary(args, summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
